# Generated by Django 2.0.2 on 2019-05-22 01:45

from django.db import migrations, models
import publish.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFPublish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pdfImagen', verbose_name='Imagen')),
                ('filepdf', models.FileField(upload_to='pdfpublish', validators=[publish.validators.validate_file_extension], verbose_name='Archivo PDF')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Orden')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha edición')),
            ],
            options={
                'verbose_name': 'revista',
                'verbose_name_plural': 'revistas',
                'ordering': ['order', 'title'],
            },
        ),
    ]
